name: "Cloud One Container Security Scan Action"
description: "Scan container images with Trend Cloud One Container Security"
inputs:
  CLOUD_ONE_API_KEY:
    description: "Cloud One API Key"
    required: true
  IMAGE:
    description: "Image to scan"
    required: true
  REGION:
    description: "Cloud One Region"
    required: true
    default: "us-1"
  MAX_TOTAL:
    description: "Max total of vulnerabilities acceptable in a images"
    required: false
    default: "0"
  MAX_CRITICAL:
    description: "Max critical vulnerabilities acceptable in a images"
    required: false
    default: "0"
  MAX_HIGH:
    description: "Max high vulnerabilities acceptable in a images"
    required: false
    default: "0"
  MAX_MEDIUM:
    description: "Max medium vulnerabilities acceptable in a images"
    required: false
    default: "0"
  MAX_LOW:
    description: "Max low vulnerabilities acceptable in a images"
    required: false
    default: "0"
  MAX_NEGLIGIBLE:
    description: "Max negligible vulnerabilities acceptable in a images"
    required: false
    default: "0"
  MAX_UNKNOWN:
    description: "Max unknown vulnerabilities acceptable in a images"
    required: false
    default: "0"
  SCAN_RESULT_ARTIFACT:
    description: "Name for the artifact generated by the scan in case you want to archive it."
    required: false
    default: "scan-result.json"
branding:
  icon: "package"
  color: "red"
runs:
  using: "docker"
  image: "docker://ghcr.io/felipecosta09/c1cs:latest"
  env:
    CLOUD_ONE_API_KEY: ${{ inputs.CLOUD_ONE_API_KEY }}
    IMAGE: ${{ inputs.IMAGE }}
    REGION: ${{ inputs.REGION }}
    MAX_TOTAL: ${{ inputs.MAX_TOTAL }}
    MAX_CRITICAL: ${{ inputs.MAX_CRITICAL }}
    MAX_HIGH: ${{ inputs.MAX_HIGH }}
    MAX_MEDIUM: ${{ inputs.MAX_MEDIUM }}
    MAX_LOW: ${{ inputs.MAX_LOW }}
    MAX_NEGLIGIBLE: ${{ inputs.MAX_NEGLIGIBLE }}
    MAX_UNKNOWN: ${{ inputs.MAX_UNKNOWN }}
    SCAN_RESULT_ARTIFACT: ${{ inputs.SCAN_RESULT_ARTIFACT }}
