name: "Cloud One Container Security Scan Action"
description: "Scan container images with Trend Micro Cloud One Container Security"
inputs:
  CLOUD_ONE_API_KEY:
    description: "Cloud One API Key"
    required: true
  IMAGE:
    description: "Image to scan"
    required: true
  REGION:
    description: "Cloud One Region"
    required: true
    default: "us-1"
  TOTAL:
    description: "Total of vulnerabilities in a images"
    required: false
    default: "0"
  MAX_CRITICAL:
    description: "Max critical vulnerabilities in a images"
    required: false
    default: "0"
  MAX_HIGH:
    description: "Max high vulnerabilities in a images"
    required: false
    default: "0"
  MAX_MEDIUM:
    description: "Max medium vulnerabilities in a images"
    required: false
    default: "0"
  MAX_LOW:
    description: "Max low vulnerabilities in a images"
    required: false
    default: "0"
  MAX_NEGLIGIBLE:
    description: "Max negligible vulnerabilities in a images"
    required: false
    default: "0"
  MAX_UNKNOWN:
    description: "Max unknown vulnerabilities in a images"
    required: false
    default: "0"
branding:
  icon: "package"
  color: "red"
runs:
  using: "docker"
  image: "docker:ghcr.io/felipecosta09/c1cs:latest"
  env:
    CLOUD_ONE_API_KEY: ${{ inputs.CLOUD_ONE_API_KEY }}
    IMAGE: ${{ inputs.IMAGE }}
    REGION: ${{ inputs.REGION }}