name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t c1cs:latest .
    - name: Tag the Docker Image
      run: docker tag c1cs:latest ghcr.io/felipecosta09/c1cs:latest
    - name: Login to GH Packages
      run: docker login ghcr.io -u felipecosta09 --password ${{ secrets.GH_TOKEN }}
    - name: Push to Packages
      run: docker push ghcr.io/felipecosta09/c1cs:latest
    
